src/CSIS/UserBundle/Entity/User.php
<?php

namespace CSIS\UserBundle\Entity;

use CSIS\EamBundle\Entity\Institution;
use CSIS\EamBundle\Entity\Laboratory;
use FOS\UserBundle\Entity\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="user")
 * @UniqueEntity("email")
 * @ORM\Entity(repositoryClass="CSIS\UserBundle\Entity\UserRepository")
 */
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255, nullable=true)
     */
    protected $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255, nullable=true)
     */
    protected $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="phone_number", type="string", length=255, nullable=true)
     */
    protected $phoneNumber;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=true)
     * @Assert\Url()
     */
    protected $url;

    /**
     * Laboratoire dans lequel travaille l'utilisateur.
     * ATTENTION : cela ne donne aucun droit à l'utilisateur
     * Les droits sont gérés via Laboratory::$owners
     *
     * @ORM\ManyToOne(targetEntity="CSIS\EamBundle\Entity\Laboratory", cascade={"persist"})
     * @ORM\JoinColumn(name="lab_id", onDelete="SET NULL", nullable=true)
     */
    protected $lab;

    /**
     * Institution dans laquelle travaille l'utilisateur
     * ATTENTION : cela ne donne aucun droit à l'utilisateur
     * Les droits sont gérés via Institution::$owners
     *
     * @ORM\ManyToOne(targetEntity="CSIS\EamBundle\Entity\Institution", cascade={"persist"})
     * @ORM\JoinColumn(name="institution_id", onDelete="SET NULL", nullable=true)
     */
    protected $institution;

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getLastName() . ' ' . $this->getFirstName() . ' <' . $this->getEmail() . '>';
    }

    /**
     * @return array
     */
    public function getFormatedRoles()
    {
        $roles = $this->getRoles();
        array_walk($roles, function(&$role) {
            $role = ucwords(strtolower(str_replace('_', ' ', substr($role, 5))));
        });

        return $roles;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set phoneNumber
     *
     * @param string $phoneNumber
     * @return User
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * Get phoneNumber
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return User
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set lab
     *
     * @param Laboratory $lab
     * @return User
     */
    public function setLab(Laboratory $lab = null)
    {
        $this->lab = $lab;

        return $this;
    }

    /**
     * Get lab
     *
     * @return Laboratory
     */
    public function getLab()
    {
        return $this->lab;
    }

    /**
     * Set institution
     *
     * @param Institution $institution
     *
     * @return User
     */
    public function setInstitution(Institution $institution = null)
    {
        $this->institution = $institution;

        return $this;
    }

    /**
     * Get institution
     *
     * @return Institution
     */
    public function getInstitution()
    {
        return $this->institution;
    }
}

src/CSIS/UserBundle/Resources/views/Admin/edit.html.twig
{% extends 'CSISUserBundle::layout.html.twig' %}

{% block fos_user_content %}

<div class="span12">
    <ul class="breadcrumb">
        <li><a href="{{ path('vitrine') }}">Vitrine</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_eam_admin_index') }}">Administration</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_index') }}">Les utilisateurs</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_show', {id: user.id}) }}">{{ user.firstName }} {{ user.lastName }}</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        {% if form.plainPassword is defined %}
            <li class="active">Édition</li>
        {% else %}
            <li class="active">Activation</li>
        {% endif %}
    </ul>
</div>

<div class="span12">
  <div class="row">
    <form action="{{ path('csis_user_edit', {'id': user.id}) }}" {{ form_enctype(form) }} class="well span4 offset2" method="POST">
      <fieldset>
          <legend>
              {% if form.plainPassword is defined %}
                  Modifier un utilisateur
              {% else %}
                  Activer un utilisateur
              {% endif %}
          </legend>
          {{ form_row(form.firstName) }}
          {{ form_row(form.lastName) }}
          {{ form_row(form.username) }}
          {{ form_row(form.email) }}
          {{ form_row(form.url) }}
          {{ form_row(form.phoneNumber) }}
          {% if form.plainPassword is defined %}
            {{ form_row(form.plainPassword) }}
          {% endif %}
          {{ form_row(form.roles) }}
          {{ form_rest(form) }}
          <br />
          {% if form.plainPassword is not defined %}
          <p class="muted">
              Un mail sera envoyé à l'utilisateur pour qu'il puisse définir son mot de passe.
          </p>
          {% endif %}
          <p>
            <a href="{{ path('csis_user_show', {'id': user.id}) }}" class="btn">
              <i class="icon-chevron-left"></i>&nbsp;Annuler
            </a>
            <button type="submit" class="btn btn-success">
              <i class="icon-edit icon-white"></i>&nbsp;{% if form.plainPassword is defined %}Modifier{% else %}Activer{% endif %}
            </button>
          </p>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

src/CSIS/UserBundle/Resources/views/Admin/editInstitution.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}

<div class="span12">
    <ul class="breadcrumb">
        <li><a href="{{ path('vitrine') }}">Vitrine</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_eam_admin_index') }}">Administration</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_index') }}">Les utilisateurs</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_show', {id: user.id}) }}">{{ user.firstName }} {{ user.lastName }}</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li class="active">Choix de l'établissement</li>
    </ul>
</div>

<form class="well span9 offset1" action="{{ path('csis_user_edit_institution', {'id': user.id}) }}" {{ form_enctype(form) }} method="POST">
    <fieldset>
      <legend>Modifier l'établissement de l'utilisateur {{ user.lastname}} {{ user.firstname }}</legend>
      {{ form_widget(form) }}
      <br />
      <div>
          <input class="btn btn-success" type="submit" value="Continuer" />
      </div>
    </fieldset>
</form>

{% endblock %}

src/CSIS/UserBundle/Resources/views/Admin/editInstitution.html.twig.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}

<form class="well span9 offset1" action="{{ path('csis_user_edit_institution', {'username': user.username}) }}" {{ form_enctype(form) }} method="POST">
    <fieldset>
      <legend>Modifier l'établissement de l'utilisateur {{ user.lastname}} {{ user.firstname }}</legend>
      {{ form_widget(form) }}
      <br />
      <div>
          <input class="btn btn-success" type="submit" value="Continuer" />
      </div>
    </fieldset>
</form>

{% endblock %}

src/CSIS/UserBundle/Resources/views/Admin/editLab.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}

<div class="span12">
    <ul class="breadcrumb">
        <li><a href="{{ path('vitrine') }}">Vitrine</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_eam_admin_index') }}">Administration</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_index') }}">Les utilisateurs</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_show', {id: user.id}) }}">{{ user.firstName }} {{ user.lastName }}</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li class="active">Choix du laboratoire</li>
    </ul>
</div>

<form class="well span9 offset1" action="{{ path('csis_user_edit_lab', {'id': user.id}) }}" {{ form_enctype(form) }} method="POST">
    <fieldset>
      <legend>Modifier le laboratoire de l'utilisateur {{ user.lastName}} {{ user.firstName }}</legend>
      {{ form_widget(form) }}
      <p class="help-block">Vous voyez les laboratoires de l'institution gérée par l'utilisateur, le laboratoire géré par l'utilisateur</p>
      <br />
      <div>
          <input class="btn btn-success" type="submit" value="Continuer" />
      </div>
    </fieldset>
</form>

{% endblock %}

src/CSIS/UserBundle/Resources/views/Admin/editLab.html.twig.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}

<form class="well span9 offset1" action="{{ path('csis_user_edit_lab', {'username': user.username}) }}" {{ form_enctype(form) }} method="POST">
    <fieldset>
      <legend>Modifier le aboratoire de l'utilisateur {{ user.lastname}} {{ user.firstname }}</legend>
      {{ form_widget(form) }}
      <br />
      <div>
          <input class="btn btn-success" type="submit" value="Continuer" />
      </div>
    </fieldset>
</form>

{% endblock %}

src/CSIS/UserBundle/Resources/views/Admin/index.html.twig
{% extends 'CSISUserBundle::layout.html.twig' %}

{% block csis_body %}
<div class="row">

    <div class="span12">
        <ul class="breadcrumb">
            <li><a href="{{ path('vitrine') }}">Vitrine</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
            <li><a href="{{ path('csis_eam_admin_index') }}">Administration</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
            <li class="active">Les utilisateurs</li>
        </ul>
    </div>

  <div class="span12">
      
    <h2>Liste des utilisateurs</h2>

    <table class="table table-hover table-striped csis-datatable">
      <thead>
        <tr>
          <th>#</th>
          <th>Nom Prénom</th>
          <th>Email</th>
          <th>Laboratoire ou Établissement</th>
          <th>Téléphone</th>
          <th>Voir</th>
          <th>État</th>
        </tr>
      </thead>
      <tbody>
      {% for user in users %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ user.lastName }} {{ user.firstName }}</td>
          <td>{{ user.email }}</td>
          <td>
            {% if user.lab %}
              <a href="{{ path('laboratory_show', {id: user.lab.id}) }}">{{ user.lab }}</a>
            {% elseif user.institution %}
              <a href="{{ path('institution_show', {id: user.institution.id}) }}">{{ user.institution }}</a>
            {% endif %}
          </td>
          <td>{{ user.phoneNumber }}</td>
          <td>
            <a href="{{ path('csis_user_show', {'id' : user.id}) }}" data-toggle="tooltip" title="Voir">
              <i class="icon-eye-open"></i>
            </a>
          </td>
          <td>
            {% if user.enabled %}
              <span style="display: none;">OK</span>
              <i class='icon icon-ok' data-toggle="tooltip" title="Compte activé"></i>
            {% else %}
              <span style="display: none;">KO</span>
              <i class='icon icon-ban-circle' data-toggle="tooltip" title="Compte désactivé"></i>
            {% endif %}
          </td>
        </tr>
      {% else %}
        <tr>
          <td colspan="6">
            <strong>Vous n'avez aucun utilisateur à afficher pour cette page !</strong><br />
            <a href="{{ path('csis_user_index') }}">Retour</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

  </div>
</div>
{% endblock %}

src/CSIS/UserBundle/Resources/views/Admin/new.html.twig
{% extends 'CSISUserBundle::layout.html.twig' %}

{% trans_default_domain 'FOSUserBundle' %}

{% block fos_user_content %}
<div class="span12">
  <div class="white-panel">
    
    <h1>{{ 'new.title'|trans({}, 'user_admin')}}</h1>
    
    <form action="{{ path('hydrodyn_user_admin_new') }}" {{ form_enctype(form) }} method="POST">
      {{ form_widget(form) }}
      <p class="muted">
        {{ 'user.rolesHelp'|trans({}, 'user_admin')|nl2br }}
      </p>
      <div>
        <input type="submit" value="{{ 'registration.submit'|trans }}" class="btn btn-success"/>
      </div>
    </form>
    
  </div>
</div>
{% endblock fos_user_content %}

src/CSIS/UserBundle/Resources/views/Admin/show.html.twig
{% extends 'CSISUserBundle::layout.html.twig' %}

{% block fos_user_content %}

<div class="span12">
    <ul class="breadcrumb">
        <li><a href="{{ path('vitrine') }}">Vitrine</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_eam_admin_index') }}">Administration</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li><a href="{{ path('csis_user_index') }}">Les utilisateurs</a> <span class="divider"><i class="icon icon-chevron-right"></i></span></li>
        <li class="active">{{ user.firstName }} {{ user.lastName }}</li>
    </ul>
</div>

<div class="span12">
  <h2>Utilisateur</h2>

  <div class="well">
    {% if is_granted('ROLE_GEST_USER') and not user.enabled %}
      <p class="text-error">Ce compte n'a pas encore été activé, car il manque des informations sur l'utilisateur. Vous pouvez activer ce compte en cliquant sur "Actier l'utilisateur", vous pourrez alors soit définir un mot de passe, soit envoyer un mail à l'utilisateur.</p>
    {%  endif %}

    <dl class="dl-horizontal">
      <dt>Prénom</dt>
      <dd>{{ user.firstName }}</dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Nom</dt>
      <dd>{{ user.lastName }}</dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>{{ 'profile.show.username'|trans({}, 'FOSUserBundle') }}</dt>
      <dd>{{ user.username }}</dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>{{ 'profile.show.email'|trans({}, 'FOSUserBundle') }}</dt>
      <dd>{{ user.emailCanonical }}</dd>
    </dl>

    {% if is_granted('ROLE_GEST_USER') %}
      <dl class="dl-horizontal">
        <dt>Rôles</dt>
          <dd>
            <ul>
              {% for role in user.formatedRoles %}
                <li>{{ role }}</li>
              {% endfor %}
            </ul>
          </dd>
      </dl>
    {% endif %}

    <dl class="dl-horizontal">
      <dt>Laboratoire</dt>
      <dd>{{ user.lab }}</dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Établissement</dt>
      <dd>{{ user.institution }}</dd>
    </dl>
  </div>

  {% if is_granted('ROLE_GEST_USER') %}
    <form action="{{ path('csis_user_delete', {'id': user.id}) }}" {{ form_enctype(delete_form) }} method="POST">
      <a href="{{ path('csis_user_index') }}" class="btn">
        <i class="icon-chevron-left"></i>&nbsp;Retour liste utilisateurs
      </a>
      {% if user.enabled %}
          <a href="{{ path('csis_user_edit', {'id': user.id}) }}" class="btn btn-success">
            <i class="icon-edit icon-white"></i>&nbsp;Modifier l'utilisateur
          </a>
      {% else %}
          <a href="{{ path('csis_user_edit', {'id': user.id}) }}" class="btn btn-success">
            <i class="icon-arrow-up icon-white"></i>&nbsp;Activer l'utilisateur
          </a>
      {% endif %}
      <button type="submit" class="btn btn-warning">
        <i class="icon-trash icon-white"></i>&nbsp;Supprimer l'utilisateur
      </button>
      {{ form_rest(delete_form) }}
    </form>
  {% endif %}
</div>
{% endblock %}